# Basic Python

## 1. Split this string

In [17]:
s = "Hi there Sam!"

In [18]:
Output=s.split()
print(Output)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [19]:
planet = "Earth"
diameter = 12742

In [20]:
print("The diameter of",planet,"is",diameter,"kilometers")

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [21]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [22]:
print(d["k1"][3]['tricky'][3]['target'][3])

hello


# Numpy

In [23]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [24]:
zeros=np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
Fives=np.ones(10)*5
print(Fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [26]:
even=np.arange(20,35,2)
print(even)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
mat=np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [31]:
import pandas as pd


In [33]:
dataframe=[['Hello',1],['NALAIYA',2],['MUTHALVAN',3]]
frame=pd.DataFrame(dataframe,columns=['WORDS','NUMBER'])
print(frame)

       WORDS  NUMBER
0      Hello       1
1    NALAIYA       2
2  MUTHALVAN       3


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [34]:
series_of_dates=pd.date_range(start="2023-01-01",end="2023-02-10")
print(series_of_dates)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [40]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [41]:
Two_data = pd.DataFrame(lists, columns =['NUMBER', 'NAME', 'VALUE']) 
print(Two_data)

   NUMBER NAME  VALUE
0       1  aaa     22
1       2  bbb     25
2       3  ccc     24
